name: Databricks CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "Databricks/**"
      - "resources/**"
      - "databricks.yml"
      - ".github/workflows/databricks-cicd.yml"

  pull_request:
    branches:
      - main
    paths:
      - "Databricks/**"
      - "resources/**"
      - "databricks.yml"

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # ---------------------------------------------------------
  # CI - Validate Python code
  # ---------------------------------------------------------
  validate:
    runs-on: ubuntu-latest
    environment: dev

    env:
        DATABRICKS_AUTH_TYPE: github-oidc
        DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
        DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Validate Databricks Python files
      run: |
        find Databricks -name "*.py" -print -exec python -m py_compile {} \;

    - name: Install Databricks CLI
      uses: databricks/setup-cli@main

    - name: Validate Databricks bundle
      run: databricks bundle validate -t dev


  # ---------------------------------------------------------
  # CD - Validate and deploy Databricks bundle
  # ---------------------------------------------------------
  deploy:
    needs: validate

    # Deploy only when code is pushed/merged to main.
    # Do not deploy from pull requests.
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest
    environment: dev

    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Validate Databricks bundle
        run: databricks bundle validate -t dev

      - name: Deploy Databricks bundle
        run: databricks bundle deploy -t dev
    
      - name: Run Wistia pipeline
        run: databricks bundle run -t dev wistia_pipeline

      - name: Run Calendly pipeline
        run: databricks bundle run -t dev calendly_pipeline

      - name: Show deployed resources
        run: databricks bundle summary -t dev
