name: Wistia Glue CI/CD

on:
  push:
    branches:
      - main
    paths:
      - "glue/wistia-api-ingestion.py"

  pull_request:
    branches:
      - main
    paths:
      - "glue/wistia-api-ingestion.py"

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Validate Python syntax
        run: |
          python -m py_compile glue/wistia-api-ingestion.py